# Generated by Django 4.2.23 on 2025-06-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tamanho', models.CharField(choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], default='M', max_length=2)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
            ],
        ),
    ]
